#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

fsmonitor.backend = "watchman"

[ui]
pager = "delta"
diff-formatter = ":git"

[aliases]
l = ["log", "-r", "(trunk()..@):: | (trunk()..@)-"]
lpr = ["log", "-r", "pr_base()-..@"]
bl = ["bookmark", "list", "--sort", "committer-date-"]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@"]
tug- = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[revset-aliases]
"pr_head()" = "heads(trunk()..@ & tracked_remote_bookmarks())"
"pr_base()" = "coalesce(heads(trunk()..pr_head()- & tracked_remote_bookmarks()), trunk())"
